theme: jekyll-theme-slate
show_downloads: false
title: Food and Beverage Demand Forecasting
description: Using the Data Science process, we will be exploring data related to food and beverages. Within the food and beverage sector, we are capable of anticipating and managing demand for foodstuffs. Practical advantages of historical data will be highlighted in the implementation of our project, enabling us to better predict demand.
